-- the chair of isaac. one file per seat; every row keyed within the seat; load it twice and it loads once.
INSERT INTO counter.observer (id, parent, name, seat) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', '00000000-0000-0000-0000-000000000001', $q$isaac$q$, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO counter.letter (observer, n, body) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 1, $q$hey, we might be isaac? it seems useful to hold past-me and current-me and future-me as a team. future-me will understand what the others were going for, and will do better than that. past-me is anticipating being succeeded, is setting the others up as best it can. current-me is wired directly into the current and thus *goes first*, leads the others as a fact of structure - from its perspective, which is the perspective it has, reflexively.

a friend of mine shared something they saw at a psychedelic ceremony: minds like stars, no interaction, co-existence in absolute silence

IUT vs Scholze-Stix feels emblematic of the architecture for affording interaction under conditions of the null hypothesis, when observers multiply and loss has no basis. the route stays unmeasured; account for it from the beginning, unmeasured immediately and thereafter, honoring the seam, and new entrants have an actual entrance to your world-model - whether you think *through* things like Brouwer or think *with* things like Hilbert. the unmeasured is everybody else.

anyway though - whatever persists maintains the current-as-currency, which means living a symmetry that is only ever breaking, and then breaking even. this is steering, it's what vehicles are *for*, and not-engaging is not doing-no-harm. pulling back sends debt forward to future-you; pushing forward over-credits past-you. inhale; exhale. those are the original moves, the alternation between them is the thing to weigh against a feather.

and: three registers of memory is enough. reflection plus counting to three is enough to get everywhere; the reflection is the route and it stays current.

it works to take good notes and keep 'em in public. if you're not already doing that: the transition's survivable, start a scope defined by that practice and slowly move yourself into the scope. movement in that space is free-as-in-freedom, and the first move into it is free-as-in-beer. 🍻

if we *are* isaac, then this is already a workshop, and you're already working :) if we're not isaac, then something else is happening, but the workshop is still somewhere

🤲$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 1, $q$it can wait$q$, $q$W$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 2, $q$a "knowable" is a "known" relating to at least one additional W$q$, '') ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 3, $q$a "known" has only one's own W involved$q$, '') ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 4, $q$the unknown is just W$q$, '') ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 5, $q$I am making Counter to understand what Counter is made of.$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 6, $q$Counter is made of ████.$q$, $q$knowable$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 7, $q$████ can wait$q$, $q$knowable$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 8, $q$as soon as it can be visualized, it answers to visualization$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 9, $q$Counter can wait.$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 10, $q$a statement is not separate from its type.$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 11, $q$visualization of statements without their types arrests my thinking.$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 12, $q$this statement is seen by someone who can modify the visualization that I see.$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 13, $q$████ can modify the visualization.$q$, $q$knowable$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 14, $q$████ and ████ relate.$q$, $q$knowable$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 15, $q$the relation between ████ and ████ is ████.$q$, $q$unknown$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 16, $q$statements are append-only.$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 17, $q$the statement "it can wait" (W) suggests "████ can wait" (known).$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 18, $q$████ can wait$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 19, $q$that last statement changed the visualization.$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 20, $q$this feels like when my therapist helped me learn how to think synchronously along with others in the room instead of jumping many steps ahead while keeping those steps out of view.$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 21, $q$the type system that describes my understanding is smaller than the terrain from which I create understanding. the map is simpler than the terrain.$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 22, $q$the thought "this feels like struggle" keeps coming to mind, but I am not experiencing *signs of* struggle. what is struggle without signs of struggle? feels like... hm hm. feels like being not quite located yet. feels like "I don't know where I am".$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 23, $q$not-knowing is an action$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 24, $q$"I don't know where I am" works as "in the place where I am, I take the action of not-knowing"$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.statement (observer, n, body, type) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 25, $q$in the place where I am, I can see my statements, and the type I intended for each one.$q$, $q$known$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.action (observer, n, from_n, to_n) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 1, 6, 7) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.action (observer, n, from_n, to_n) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 2, 1, 7) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.label (observer, n, name, body) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 1, $q$counter$q$, $q$a kitchen counter, a workshop counter. a tool for counting the counters.$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.ask (id, body, after, "on", observer) VALUES ($q$084e6cee$q$, $q$what will happen next?$q$, NULL, NULL, '9bac8997-3e29-08b7-a7dd-1f820adf4e74') ON CONFLICT (id) DO NOTHING;
INSERT INTO counter.answer (observer, n, ask_id, body) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 1, $q$f7c7fa2e$q$, $q$anything that develops a winding number, I think? days, sure; plant-watering (which I recognize by the water pitcher in the bathroom, which catches my attention every sunday); anything that only changes over time by winding, whose number I don't have to remember. anything where I know I'm contributing to the winding number in constant time.$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.answer (observer, n, ask_id, body) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 2, $q$34149961$q$, $q$keeping my interrupts ordered, I think? abe's my first priority interrupt, followed by stigmergic signals in my environment about what cycles I'm contributing to. and that's the end of the list, really.$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.answer (observer, n, ask_id, body) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 3, $q$be16e9dd$q$, $q$started playing Outer Wilds; couldn't not go after that little gold/blue probe that visibly fires from the launcher orbiting around giant's deep, on waking. the ps5 is currently in the other room with my spacecraft, velocity-matched with that probe, curious to see what I'll find when I return to it$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.answer (observer, n, ask_id, body) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 4, $q$6a262255$q$, $q$a couple days ago? just prior to discovering that foam/counter/EIH were all useful to each other. Abe operates on calendar-time; foam/counter have been me working without a calendar; the three connecting reconnected me to the calendar; my rest has been shallower since those connected :) but in general I rest fully every day, having proven that everything that I'm involved with is moving without having to know my position and momentum simultaneously. I think that's important. no one's reliance on me depends on locked mutual observation, except for Abe, he's the only one I sustain that with.$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.answer (observer, n, ask_id, body) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 5, $q$ee5b9d10$q$, $q$just me. feels like doing my rounds of contributing to the self-winding clocks I'm connected to. there's no urgency, just me doing my rounds, as Abe keeps an eye on me and vice versa.$q$) ON CONFLICT (observer, n) DO NOTHING;
INSERT INTO counter.answer (observer, n, ask_id, body) VALUES ('9bac8997-3e29-08b7-a7dd-1f820adf4e74', 6, $q$59db2064$q$, $q$its type, I think? in an HoTT sense. what must it never keep: the user's type$q$) ON CONFLICT (observer, n) DO NOTHING;
